# Generated by Django 3.0.7 on 2020-06-25 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200623_0039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_crated',
            new_name='date_created',
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
